src/PreventionAdvisor/Controllers/AuthController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PreventionAdvisor.Models;
using PreventionAdvisor.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;


namespace PreventionAdvisor.Controllers
{

    //   [ValidateAntiForgeryToken]
    [Route("api/[controller]")]
    public class AuthController : Controller
    {
        private SignInManager<User> _signInManager;
        private readonly PreventionAdvisorDbContext _dbContext;

        public AuthController(SignInManager<User> signInManager, PreventionAdvisorDbContext dbContext = null)
        {
            _dbContext = dbContext;
            this._signInManager = signInManager;
        }

        [HttpPost("/api/login")]
        public async Task<ActionResult> Login(UserViewModel vm, string returnUrl) {
            var result = await _signInManager.PasswordSignInAsync(vm.Username, vm.Password, false, false);

            if (result.Succeeded)
            {

                User usr = this._dbContext.Users.Where(u => u.UserName == vm.Username).First() ;

                return Ok(Mapper.Map<UserViewModel>(usr));
            }


            return BadRequest("Failed to login");
        }

        [HttpPost("/api/logout")]
        public async Task<ActionResult> Logout() {
            if (User.Identity.IsAuthenticated) {
                await _signInManager.SignOutAsync();
            }
            return Ok();
        }

    }
}

src/PreventionAdvisor/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PreventionAdvisor.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/PreventionAdvisor/Views/Home/index.cshtml
@if (User.Identity.IsAuthenticated) {
    <div>Hi, @User.Identity.Name </div>
    <a asp-controller="Auth" asp-action="Logout">Logout</a>
}

<!DOCTYPE html>
    
<html>

<head lang="en">
    <base href="/">
    <title>Werkplek Rapporten</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="app/app.component.css" rel="stylesheet" />

    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <!-- Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
</head>

<body>
    <pm-app>Loading App...</pm-app>
</body>

</html>